---
title: "Google Pages rock"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
suppressPackageStartupMessages({
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
})
```

# Load salmon data from KNB
# This checks to see if local copy exists.  If local

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1"
# data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"
esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

#Prepare dataset for calculating medians


```{r}
median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))
  
head(median_esc)
```

# Plot escapement as a bar chart

```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```

# Now work on building a map

We're starting on daily escapement again and finding unique locations at which escapements were measured.

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)
```

## Draw map with leaflet

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
```

# Fix bad points


```{r}
locs <- locations %>% mutate(Longitude = abs(Longitude) * -1)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
```

