---
title: "Tidying Data in R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```

Read in data from [Mike Byerly. 2016. Alaska commercial salmon catches by management region (1886- 1997). urn:node:GOA. df35b.304.2.] (https://knb.ecoinformatics.org/#view/df35b.304.2).


```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```


```{r}
catch_df <- catch_df %>% 
  select(-All, -notesRegCode)

head(catch_df)

```

Move from wide to long format (using gather) and rename the catch column to reflect units


```{r}
catch_df <- catch_df %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)

unique(catch_df$species)
```

```{r}
catch_integers <- as.integer(catch_df$catch_thousands)

i <- which(is.na(catch_integers) == T)

catch_df$catch_thousands[i]

```



```{r}
catch_df <- catch_df %>%
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)

tail(catch_df)
```


```{r}
catch_summarized <- catch_df %>% 
  group_by(Region) %>% 
  summarise(mean_catch = mean(catch))

head(catch_summarized)
```

```{r}
catch_summarized_species <- catch_df %>% 
  group_by(species) %>% 
  summarise(mean_catch_species = mean(catch))

head(catch_summarized_species)
```

```{r}
catch_summarized_species <- catch_df %>% 
  group_by(Region) %>% 
  summarise(catch_low = range(catch)[1],
  catch_high = range(catch)[2])

head(catch_summarized_species)
```

```{r}
catch_summarized_region_species <- catch_df %>% 
  group_by(Region, species) %>% 
  summarise(catch_mean = mean(catch, na.rm = T), 
            catch_stdev = sd(catch, na.rm = T),
            num_obs = n()) %>% 
  #filter for Chinook
  filter(catch_mean >2000)


head(catch_summarized_region_species)
```

#joins


```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)

head(region_defs)
```

```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)

```

```{r}
catch_joined <- left_join(catch_df, region_defs, by = c("Region" = "code"))

head(catch_joined)


```

